name: resume-studio
region: nyc
services:
  - name: resume-studio-web
    dockerfile_path: Dockerfile
    http_port: 5050
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /health
    envs:
      - key: PASSCODE_HASH
      - key: FIREBASE_SERVICE_ACCOUNT
      - key: R2_ACCOUNT_ID
      - key: R2_ACCESS_KEY_ID
      - key: R2_SECRET_ACCESS_KEY
      - key: R2_BUCKET_NAME
